import { Schema, model, Document } from 'mongoose';

/**
 * Tenant model
 *
 * tenantId — human-readable prefixed string, e.g. "inst_a3f9k2xb" or "schl_7m1pq4yz".
 *            Generated by generateTenantId() at creation time.
 *            This is the identifier propagated to every other document via tenantId fields.
 *            The MongoDB _id (ObjectId) is intentionally kept as internal DB key only.
 */
export interface ITenant extends Document {
  tenantId:      string;   // e.g. inst_a3f9k2xb — the propagated tenant identifier
  name:          string;
  slug:          string;
  type?:         string;   // 'school' | 'college' | 'university' | 'institute' | 'org'
  logoUrl?:      string;
  domain?:       string;
  email?:        string;
  phone?:        string;
  address?:      string;
  affiliation?:  string;
  accreditation?: string;
  isActive:      boolean;
  onboardingComplete?: boolean;
  finalizedAt?:        Date;
  finalizedBy?:        string;
  plan?:               string;
  deletedAt?:          Date;
  deletedBy?:          string;
  deletionOtp?:            string;
  deletionOtpExpiresAt?:   Date;
  createdAt: Date;
  updatedAt: Date;
}

const TenantSchema = new Schema<ITenant>(
  {
    tenantId:      { type: String, required: true },
    name:          { type: String, required: true },
    slug:          { type: String, required: true },
    type:          { type: String },
    logoUrl:       { type: String },
    domain:        { type: String },
    email:         { type: String },
    phone:         { type: String },
    address:       { type: String },
    affiliation:   { type: String },
    accreditation: { type: String },
    isActive:      { type: Boolean, default: true },
    onboardingComplete:    { type: Boolean, default: false },
    finalizedAt:           { type: Date },
    finalizedBy:           { type: String },
    plan:                  { type: String },
    deletedAt:             { type: Date },
    deletedBy:             { type: String },
    deletionOtp:           { type: String, select: false },  // never returned in queries by default
    deletionOtpExpiresAt:  { type: Date,   select: false },
  },
  { timestamps: true },
);

// tenantId is globally unique — it IS the cross-collection tenant key
TenantSchema.index({ tenantId: 1 }, { unique: true });
// slug is tenant's URL-friendly name — globally unique
TenantSchema.index({ slug: 1 },      { unique: true });
// domain lookup (for subdomain routing)
TenantSchema.index({ domain: 1 },    { unique: true, sparse: true });

export const Tenant = model<ITenant>('Tenant', TenantSchema);
